controller_list:
  - name: fake_manipulator_controller
    type: $(arg fake_execution_type)
    joints:
      - link_01__link_02
      - link_02__link_03
      - link_03__link_04
      - link_04__link_05
initial:  # Define initial robot poses per group
  - group: manipulator
    pose: zero