manipulator_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - link_01__link_02
    - link_02__link_03
    - link_03__link_04
    - link_04__link_05
  gains:
    link_01__link_02:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_02__link_03:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_03__link_04:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    link_04__link_05:
      p: 100
      d: 1
      i: 1
      i_clamp: 1